name: Extract Windows and macOS fonts
on: [push, pull_request, workflow_dispatch]

jobs:
  extract-macos:
    runs-on: macos-11 # see: https://github.com/actions/virtual-environments#available-environments
    steps:
      - name: Extract fonts
        run: |
          mkdir fonts
          find /System/Library/Fonts -type f -exec cp {} fonts/ \;
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v2
        with:
          name: fonts-mac
          path: fonts/
  extract-windows:
    runs-on: windows-2022 # see: https://github.com/actions/virtual-environments#available-environments
    steps:
      - name: Checkout other repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.PAC }}
          path: ./repo
      - name: Extract fonts
        shell: bash
        run: |
          mkdir fonts
          find C:\\Windows\\Fonts \( -iname '*.ttf' -o -iname '*.ttc' \) -exec cp {} fonts/ \;
          cp repo/w10_basic/holomdl2.ttf fonts/holomdl2.ttf # this font is missing in Windows Enterprise
          cp repo/w10_basic/Sitka* fonts/ # these too
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v2
        with:
          name: fonts-win
          path: fonts/
  upload:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [extract-macos, extract-windows]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Compress all fonts
      run: |
        7z a fonts-mac.zip fonts-mac/*
        7z a fonts-win.zip fonts-win/*
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          fonts-mac.zip
          fonts-win.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
