name: Extract Windows and macOS fonts
on: [push, pull_request, workflow_dispatch]

jobs:
  extract-macos:
    runs-on: macos-latest
    steps:
      - name: Extract fonts
        run: |
          mkdir fonts
          find /System/Library/Fonts -type f -exec cp {} fonts/ \;
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS fonts
          path: fonts/
  extract-windows:
    runs-on: windows-latest
    steps:
      - name: Extract fonts
        run: |
          mkdir fonts
          find C:\Windows\Fonts -type f -exec cp {} fonts/ \;
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows fonts
          path: fonts/
  upload:
    runs-on: ubuntu-latest
    needs: [extract-macos, extract-windows]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Display structure of downloaded files
      run: ls -R
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: fonts-macos.zip
#          draft: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
