name: Extract Windows and macOS fonts
on: [push, pull_request, workflow_dispatch]

jobs:
  extract-macos:
    runs-on: macos-15 # see: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    steps:
      - name: Extract fonts
        run: |
          mkdir fonts
          find /System/Library/Fonts -type f -exec cp {} fonts/ \;
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v4
        with:
          name: fonts-mac
          path: fonts/
  extract-android:
    runs-on: ubuntu-latest
    steps:
      - name: Download fonts
        run: |
          mkdir android
          
          # Download noto-emoji from https://github.com/googlefonts/noto-emoji
          curl -sLo android/NotoColorEmoji.ttf https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf

          # Download roboto-3-classic from https://github.com/googlefonts/roboto-3-classic
          curl -sLo roboto.zip $(curl -s https://api.github.com/repos/googlefonts/roboto-3-classic/releases/latest | jq -r '.assets[0].browser_download_url')
          unzip -j -q roboto.zip "android/static/*" -d android
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v4
        with:
          name: fonts-android
          path: android/
  extract-windows:
    runs-on: windows-2025 # see: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    steps:
      - name: Checkout other repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.PAC }}
          path: ./repo
      - name: Extract fonts
        shell: bash
        run: |
          mkdir win
          find C:\\Windows\\Fonts \( -iname '*.ttf' -o -iname '*.ttc' \) -exec cp {} win/ \;
          cp repo/w10_basic/holomdl2.ttf win/ # this font is missing in Windows Enterprise
          cp repo/w10_basic/Sitka* win/ # these too
          mkdir office
          for i in $(diff -r repo/w10_basic repo/w10_office_extended | grep w10_office_extended | awk '{print $4}'); do cp repo/w10_office_extended/$i office/; done
          mkdir win11
          cp repo/w11/SitkaVF* win11/
          cp repo/w11/SegUIVar.ttf win11/
          cp repo/w11/SegoeIcons.ttf win11/
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v4
        with:
          name: fonts-win
          path: win/
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v4
        with:
          name: fonts-office
          path: office/
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v4
        with:
          name: fonts-win11
          path: win11/
  upload:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [extract-macos, extract-windows, extract-android]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
    - name: Compress all fonts
      run: |
        7z a fonts-mac.zip fonts-mac/*
        7z a fonts-win.zip fonts-win/*
        7z a fonts-win11.zip fonts-win11/*
        7z a fonts-office.zip fonts-office/*
        7z a fonts-android.zip fonts-android/*
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          fonts-mac.zip
          fonts-win.zip
          fonts-win11.zip
          fonts-office.zip
          fonts-android.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
