name: Extract Windows and macOS fonts
on: [push, pull_request, workflow_dispatch]

jobs:
  extract-macos:
    runs-on: macos-latest
    steps:
      - name: Extract fonts
        run: |
          mkdir fonts
          find /System/Library/Fonts -type f -exec cp {} fonts/ \;
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v2
        with:
          name: fonts-mac
          path: fonts/
  extract-windows:
    runs-on: windows-latest
    steps:
      - name: Extract fonts
        shell: bash
        run: |
          mkdir fonts
          find C:\\Windows\\Fonts -iname '*.ttf' -exec cp {} fonts/ \;
      - name: Upload fonts artifact
        uses: actions/upload-artifact@v2
        with:
          name: fonts-win
          path: fonts/
  upload:
    runs-on: ubuntu-latest
    needs: [extract-macos, extract-windows]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Compress all fonts
      run: |
        7z a fonts-mac.zip fonts-mac/*
        7z a fonts-win.zip fonts-win/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            fonts-macos.zip
            fonts-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
